all: abstract_factory abstract_factory_2

abstract_factory: abstract_factory.cpp
	g++ -std=c++11 abstract_factory.cpp -o abstract_factory

abstract_factory_2: abstract_factory_2.cpp
	g++ -std=c++11 abstract_factory_2.cpp -o abstract_factory_2

clean:
	rm abstract_factory abstract_factory_2
