all: strategy strategy_as_function

strategy: strategy.cpp
	g++ -std=c++11 strategy.cpp -o strategy

strategy_as_function: strategy_as_function.cpp
	g++ -std=c++11 strategy_as_function.cpp -o strategy_as_function


clean:
	rm strategy
