all:
	cd 1.iterator && make
	cd 2.chain_of_responsibility && make
	cd 3.observer && make
	cd 4.command && make
	cd 5.memento && make
	cd 6.state && make
	cd 7.strategy && make


clean:
	cd 1.iterator && make clean
	cd 2.chain_of_responsibility && make clean
	cd 3.observer && make clean
	cd 4.command && make clean
	cd 5.memento && make clean
	cd 6.state && make clean
	cd 7.strategy && make clean
