all: adaptor_composition adaptor_inheritance

adaptor_composition: adaptor_composition.cpp
	g++ -std=c++11 adaptor_composition.cpp -o adaptor_composition

adaptor_inheritance: adaptor_inheritance.cpp
	g++ -std=c++11 adaptor_inheritance.cpp -o adaptor_inheritance

clean:
	rm adaptor_composition adaptor_inheritance
