all: composite composite_2

composite: composite.cpp
	g++ -std=c++11 composite.cpp -o composite


composite_2: composite_2.cpp
	g++ -std=c++11 composite_2.cpp -o composite_2

clean:
	rm composite composite_2
