all: fabric_methode fabric_methode_2 fabric_methode_3

fabric_methode: fabric_methode.cpp
	g++ -std=c++11 fabric_methode.cpp -o fabric_methode

fabric_methode_2: fabric_methode_2.cpp
	g++ -std=c++11 fabric_methode_2.cpp -o fabric_methode_2

fabric_methode_3: fabric_methode_3.cpp
	g++ -std=c++11 fabric_methode_3.cpp -o fabric_methode_3

clean:
	rm fabric_methode fabric_methode_2 fabric_methode_3
