all: decorator decorator_2

decorator: decorator.cpp
	g++ -std=c++11 decorator.cpp -o decorator


decorator_2: decorator_2.cpp
	g++ -std=c++11 decorator_2.cpp -o decorator_2

clean:
	rm decorator decorator_2
